name: Deploy to Cloud Run loh yaa

env:
  SERVICE_NAME: portfolio-service
  PROJECT_ID: mlpt-cloudteam-migration
  DOCKER_IMAGE_URL: asia-southeast2-docker.pkg.dev/mlpt-cloudteam-migration/portfolio-repo

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  dockerize-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Set Up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated \

  