name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio-flask:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for gcr
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy portfolio-flask \
            --image "$IMAGE" \
            --platform managed \
            --region "$GCP_REGION" \
            --allow-unauthenticated \
            --quiet

      - name: Smoke test Cloud Run service
        run: |
          set -e
          # get service URL
          URL=$(gcloud run services describe portfolio-flask --platform managed --region "$GCP_REGION" --format 'value(status.url)')
          echo "Service URL: $URL"

          # simple retry loop: try up to 10 times, 5s between tries
          n=0
          until [ $n -ge 10 ]
          do
            echo "Attempt $((n+1)) to curl $URL"
            if curl -fsS -m 10 "$URL" >/dev/null; then
              echo "Smoke test passed"
              exit 0
            fi
            n=$((n+1))
            sleep 5
          done

          echo "Smoke test failed: service did not respond with HTTP 200 within retries"
          exit 1
