name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for gcr
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio-flask:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio-flask:${{ github.sha }}
          gcloud run deploy portfolio-flask \
            --image $IMAGE \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --quiet
